version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_management_system_ci
    ports:
      - 5432:5432

  app:
    build: .
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:password@db:5432/task_management_system_ci
      SECRET_KEY_BASE: test_secret_key_base
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
