version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_management_system_production
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      - RAILS_ENV=production
      - TASK_MANAGEMENT_SYSTEM_DATABASE_USERNAME=${TASK_MANAGEMENT_SYSTEM_DATABASE_USERNAME}
      - TASK_MANAGEMENT_SYSTEM_DATABASE_PASSWORD=${TASK_MANAGEMENT_SYSTEM_DATABASE_PASSWORD}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
