name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up timestamp
      run: echo "IMAGE_TAG=my-image-name:$(date +%s)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_TAG }}

    - name: Run the Docker container
      run: docker run -d --name my-container ${{ env.IMAGE_TAG }} tail -f /dev/null

    - name: Check container status
      run: docker ps -a

    - name: Install dependencies
      run: docker exec my-container bundle install

    - name: Run RSpec tests
      run: docker exec my-container bundle exec rspec

    - name: Run RuboCop
      run: docker exec my-container bundle exec rubocop

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push the Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/my-image-name:latest
