name: CI

on:
  push:
    branches: 
      - '*'  # 監聽所有分支
  pull_request:
    branches: 
      - '*'  # 監聽所有分支

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: task_management_system_ci
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.0' # 你正在使用的 Ruby 版本

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build Docker image
      run: docker build -t my-image-name .

    - name: Run Docker container
      run: docker run -d --name my-container -e RAILS_ENV=test -e SECRET_KEY_BASE=test_secret_key_base --link db:db my-image-name tail -f /dev/null

    - name: Run RuboCop
      run: docker exec my-container bundle exec rubocop

    - name: Set up database
      run: docker exec my-container bin/rails db:create db:schema:load

    - name: Run RSpec tests
      run: docker exec my-container bundle exec rspec
