name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Compose
      run: sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose

    - name: Build and run services
      run: docker-compose up -d --build

    - name: Wait for DB to be ready
      run: docker-compose run app bash -c 'while ! pg_isready -h db -p 5432 -U postgres; do sleep 1; done'

    - name: Set up database
      run: docker-compose run app bin/rails db:create db:schema:load

    - name: Run RuboCop
      run: docker-compose run app bundle exec rubocop

    - name: Run RSpec tests
      run: docker-compose run app bundle exec rspec

    - name: Shut down services
      run: docker-compose down
