name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache bundle dependencies
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-bundler-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-bundler-

    - name: Cache Yarn dependencies
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Build and run services
      run: docker-compose up -d --build

    - name: Wait for DB to be ready
      run: docker-compose run app bash -c 'while ! pg_isready -h db -p 5432 -U postgres; do sleep 1; done'

    - name: Set up database
      run: docker-compose run app bin/rails db:setup
      env:
        TASK_MANAGEMENT_SYSTEM_DATABASE_USERNAME: ${{ secrets.TASK_MANAGEMENT_SYSTEM_DATABASE_USERNAME }}
        TASK_MANAGEMENT_SYSTEM_DATABASE_PASSWORD: ${{ secrets.TASK_MANAGEMENT_SYSTEM_DATABASE_PASSWORD }}
        SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}

    - name: Run RuboCop
      run: docker-compose run app bundle exec rubocop

    - name: Run RSpec tests
      run: docker-compose run app bundle exec rspec

    - name: Shut down services
      run: docker-compose down
