name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      TASK_MANAGEMENT_SYSTEM_DATABASE_USERNAME: ${{ secrets.TASK_MANAGEMENT_SYSTEM_DATABASE_USERNAME }}
      TASK_MANAGEMENT_SYSTEM_DATABASE_PASSWORD: ${{ secrets.TASK_MANAGEMENT_SYSTEM_DATABASE_PASSWORD }}
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.0

    - name: Cache bundle dependencies
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-bundler-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-bundler-

    - name: Install bundle dependencies
      run: bundle install --jobs=4 --retry=5

    - name: Run RuboCop for code linting
      run: bundle exec rubocop

    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Cache Yarn dependencies
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: |
        yarn install --frozen-lockfile

    - name: Build Docker images
      run: docker-compose build

    - name: Precompile assets
      run: docker-compose run --rm app bash -c "SECRET_KEY_BASE=dummy_secret_key_base RAILS_ENV=production bundle exec rails assets:precompile"

    - name: Set up database for CI environment
      run: docker-compose run --rm app bash -c "RAILS_ENV=ci bundle exec rails db:setup"

    - name: Run RuboCop for code linting
      run: docker-compose run --rm app bundle exec rubocop

    - name: Run tests
      run: docker-compose run --rm app bundle exec rspec

    - name: Shut down services
      run: docker-compose down --volumes --remove-orphans
