name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.10.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose version

    - name: Ensure bundle and node_modules directories exist
      run: |
        mkdir -p vendor/bundle
        mkdir -p node_modules

    - name: Cache bundle dependencies
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-bundler-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-bundler-

    - name: Cache Yarn dependencies
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install Yarn
      run: |
        curl -o- -L https://yarnpkg.com/install.sh | bash
        yarn install --frozen-lockfile

    - name: Build and run services
      run: docker-compose up -d --build

    - name: Wait for DB to be ready
      run: docker-compose run app bash -c 'while ! pg_isready -h db -p 5432 -U postgres; do sleep 1; done'

    - name: Set up database
      run: docker-compose run app bin/rails db:setup

    - name: Run RuboCop
      run: docker-compose run app bundle exec rubocop

    - name: Run RSpec tests
      run: docker-compose run app bundle exec rspec

    - name: Shut down services
      run: docker-compose down
